# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abstract_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitives import time_primitives_pb2 as primitives_dot_time__primitives__pb2
import metadata_map_pb2 as metadata__map__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='abstract_message.proto',
  package='messages',
  syntax='proto3',
  serialized_options=_b('\n\036jpl.gds.serialization.messagesB$ProtoBufAbstractMessageSerializationH\001P\001'),
  serialized_pb=_b('\n\x16\x61\x62stract_message.proto\x12\x08messages\x1a primitives/time_primitives.proto\x1a\x12metadata_map.proto\"l\n\x15Proto3AbstractMessage\x12\x11\n\teventTime\x18\x01 \x01(\x03\x12\x0f\n\x07\x66romSse\x18\x02 \x01(\x08\x12/\n\ncontextMap\x18\x04 \x01(\x0b\x32\x1b.metadata.Proto3MetadataMapBJ\n\x1ejpl.gds.serialization.messagesB$ProtoBufAbstractMessageSerializationH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[primitives_dot_time__primitives__pb2.DESCRIPTOR,metadata__map__pb2.DESCRIPTOR,])




_PROTO3ABSTRACTMESSAGE = _descriptor.Descriptor(
  name='Proto3AbstractMessage',
  full_name='messages.Proto3AbstractMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventTime', full_name='messages.Proto3AbstractMessage.eventTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromSse', full_name='messages.Proto3AbstractMessage.fromSse', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contextMap', full_name='messages.Proto3AbstractMessage.contextMap', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=198,
)

_PROTO3ABSTRACTMESSAGE.fields_by_name['contextMap'].message_type = metadata__map__pb2._PROTO3METADATAMAP
DESCRIPTOR.message_types_by_name['Proto3AbstractMessage'] = _PROTO3ABSTRACTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3AbstractMessage = _reflection.GeneratedProtocolMessageType('Proto3AbstractMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ABSTRACTMESSAGE,
  __module__ = 'abstract_message_pb2'
  # @@protoc_insertion_point(class_scope:messages.Proto3AbstractMessage)
  ))
_sym_db.RegisterMessage(Proto3AbstractMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
