# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitives import alarm_primitives_pb2 as primitives_dot_alarm__primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alarm_value.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\033jpl.gds.alarm.serializationH\001'),
  serialized_pb=_b('\n\x11\x61larm_value.proto\x1a!primitives/alarm_primitives.proto\"\x97\x01\n\x10Proto3AlarmValue\x12\x11\n\tisInAlarm\x18\x01 \x01(\x08\x12\x0e\n\x06isOnEu\x18\x02 \x01(\x08\x12\x1e\n\x04type\x18\x03 \x01(\x0e\x32\x10.Proto3AlarmType\x12 \n\x05level\x18\x04 \x01(\x0e\x32\x11.Proto3AlarmLevel\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07\x61larmId\x18\x06 \x01(\tB\x1f\n\x1bjpl.gds.alarm.serializationH\x01\x62\x06proto3')
  ,
  dependencies=[primitives_dot_alarm__primitives__pb2.DESCRIPTOR,])




_PROTO3ALARMVALUE = _descriptor.Descriptor(
  name='Proto3AlarmValue',
  full_name='Proto3AlarmValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isInAlarm', full_name='Proto3AlarmValue.isInAlarm', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isOnEu', full_name='Proto3AlarmValue.isOnEu', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Proto3AlarmValue.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='Proto3AlarmValue.level', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='Proto3AlarmValue.state', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmId', full_name='Proto3AlarmValue.alarmId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=208,
)

_PROTO3ALARMVALUE.fields_by_name['type'].enum_type = primitives_dot_alarm__primitives__pb2._PROTO3ALARMTYPE
_PROTO3ALARMVALUE.fields_by_name['level'].enum_type = primitives_dot_alarm__primitives__pb2._PROTO3ALARMLEVEL
DESCRIPTOR.message_types_by_name['Proto3AlarmValue'] = _PROTO3ALARMVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3AlarmValue = _reflection.GeneratedProtocolMessageType('Proto3AlarmValue', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ALARMVALUE,
  __module__ = 'alarm_value_pb2'
  # @@protoc_insertion_point(class_scope:Proto3AlarmValue)
  ))
_sym_db.RegisterMessage(Proto3AlarmValue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
