# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm_statistics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import alarm_value_pb2 as alarm__value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alarm_statistics.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\033jpl.gds.alarm.serializationH\001'),
  serialized_pb=_b('\n\x16\x61larm_statistics.proto\x1a\x11\x61larm_value.proto\"\xa7\x01\n\x15Proto3AlarmStatistics\x12\x1b\n\x13\x63onsecutiveNoAlarms\x18\x01 \x01(\x05\x12\x1c\n\x14\x63onsecutiveRedAlarms\x18\x02 \x01(\x05\x12\x1f\n\x17\x63onsecutiveYellowAlarms\x18\x03 \x01(\x05\x12\"\n\x05value\x18\x04 \x01(\x0b\x32\x11.Proto3AlarmValueH\x00\x42\x0e\n\x0c\x63urrentValue\"\xc0\x01\n&Proto3MonitorAlarmStatisticsStationMap\x12K\n\nintegerMap\x18\x01 \x03(\x0b\x32\x37.Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry\x1aI\n\x0fIntegerMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.Proto3AlarmStatistics:\x02\x38\x01\"\xbd\x01\n\x1fProto3MonitorAlarmStatisticsMap\x12@\n\x08statsMap\x18\x01 \x03(\x0b\x32..Proto3MonitorAlarmStatisticsMap.StatsMapEntry\x1aX\n\rStatsMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.Proto3MonitorAlarmStatisticsStationMap:\x02\x38\x01\"\x9e\x01\n\x18Proto3AlarmStatisticsMap\x12\x39\n\x08statsMap\x18\x01 \x03(\x0b\x32\'.Proto3AlarmStatisticsMap.StatsMapEntry\x1aG\n\rStatsMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.Proto3AlarmStatistics:\x02\x38\x01\x42\x1f\n\x1bjpl.gds.alarm.serializationH\x01\x62\x06proto3')
  ,
  dependencies=[alarm__value__pb2.DESCRIPTOR,])




_PROTO3ALARMSTATISTICS = _descriptor.Descriptor(
  name='Proto3AlarmStatistics',
  full_name='Proto3AlarmStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consecutiveNoAlarms', full_name='Proto3AlarmStatistics.consecutiveNoAlarms', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consecutiveRedAlarms', full_name='Proto3AlarmStatistics.consecutiveRedAlarms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consecutiveYellowAlarms', full_name='Proto3AlarmStatistics.consecutiveYellowAlarms', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3AlarmStatistics.value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='currentValue', full_name='Proto3AlarmStatistics.currentValue',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=46,
  serialized_end=213,
)


_PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY = _descriptor.Descriptor(
  name='IntegerMapEntry',
  full_name='Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=408,
)

_PROTO3MONITORALARMSTATISTICSSTATIONMAP = _descriptor.Descriptor(
  name='Proto3MonitorAlarmStatisticsStationMap',
  full_name='Proto3MonitorAlarmStatisticsStationMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='integerMap', full_name='Proto3MonitorAlarmStatisticsStationMap.integerMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=408,
)


_PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY = _descriptor.Descriptor(
  name='StatsMapEntry',
  full_name='Proto3MonitorAlarmStatisticsMap.StatsMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto3MonitorAlarmStatisticsMap.StatsMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3MonitorAlarmStatisticsMap.StatsMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=600,
)

_PROTO3MONITORALARMSTATISTICSMAP = _descriptor.Descriptor(
  name='Proto3MonitorAlarmStatisticsMap',
  full_name='Proto3MonitorAlarmStatisticsMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statsMap', full_name='Proto3MonitorAlarmStatisticsMap.statsMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=600,
)


_PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY = _descriptor.Descriptor(
  name='StatsMapEntry',
  full_name='Proto3AlarmStatisticsMap.StatsMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto3AlarmStatisticsMap.StatsMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3AlarmStatisticsMap.StatsMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=761,
)

_PROTO3ALARMSTATISTICSMAP = _descriptor.Descriptor(
  name='Proto3AlarmStatisticsMap',
  full_name='Proto3AlarmStatisticsMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statsMap', full_name='Proto3AlarmStatisticsMap.statsMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=761,
)

_PROTO3ALARMSTATISTICS.fields_by_name['value'].message_type = alarm__value__pb2._PROTO3ALARMVALUE
_PROTO3ALARMSTATISTICS.oneofs_by_name['currentValue'].fields.append(
  _PROTO3ALARMSTATISTICS.fields_by_name['value'])
_PROTO3ALARMSTATISTICS.fields_by_name['value'].containing_oneof = _PROTO3ALARMSTATISTICS.oneofs_by_name['currentValue']
_PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY.fields_by_name['value'].message_type = _PROTO3ALARMSTATISTICS
_PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY.containing_type = _PROTO3MONITORALARMSTATISTICSSTATIONMAP
_PROTO3MONITORALARMSTATISTICSSTATIONMAP.fields_by_name['integerMap'].message_type = _PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY
_PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY.fields_by_name['value'].message_type = _PROTO3MONITORALARMSTATISTICSSTATIONMAP
_PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY.containing_type = _PROTO3MONITORALARMSTATISTICSMAP
_PROTO3MONITORALARMSTATISTICSMAP.fields_by_name['statsMap'].message_type = _PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY
_PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY.fields_by_name['value'].message_type = _PROTO3ALARMSTATISTICS
_PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY.containing_type = _PROTO3ALARMSTATISTICSMAP
_PROTO3ALARMSTATISTICSMAP.fields_by_name['statsMap'].message_type = _PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY
DESCRIPTOR.message_types_by_name['Proto3AlarmStatistics'] = _PROTO3ALARMSTATISTICS
DESCRIPTOR.message_types_by_name['Proto3MonitorAlarmStatisticsStationMap'] = _PROTO3MONITORALARMSTATISTICSSTATIONMAP
DESCRIPTOR.message_types_by_name['Proto3MonitorAlarmStatisticsMap'] = _PROTO3MONITORALARMSTATISTICSMAP
DESCRIPTOR.message_types_by_name['Proto3AlarmStatisticsMap'] = _PROTO3ALARMSTATISTICSMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3AlarmStatistics = _reflection.GeneratedProtocolMessageType('Proto3AlarmStatistics', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ALARMSTATISTICS,
  __module__ = 'alarm_statistics_pb2'
  # @@protoc_insertion_point(class_scope:Proto3AlarmStatistics)
  ))
_sym_db.RegisterMessage(Proto3AlarmStatistics)

Proto3MonitorAlarmStatisticsStationMap = _reflection.GeneratedProtocolMessageType('Proto3MonitorAlarmStatisticsStationMap', (_message.Message,), dict(

  IntegerMapEntry = _reflection.GeneratedProtocolMessageType('IntegerMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY,
    __module__ = 'alarm_statistics_pb2'
    # @@protoc_insertion_point(class_scope:Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry)
    ))
  ,
  DESCRIPTOR = _PROTO3MONITORALARMSTATISTICSSTATIONMAP,
  __module__ = 'alarm_statistics_pb2'
  # @@protoc_insertion_point(class_scope:Proto3MonitorAlarmStatisticsStationMap)
  ))
_sym_db.RegisterMessage(Proto3MonitorAlarmStatisticsStationMap)
_sym_db.RegisterMessage(Proto3MonitorAlarmStatisticsStationMap.IntegerMapEntry)

Proto3MonitorAlarmStatisticsMap = _reflection.GeneratedProtocolMessageType('Proto3MonitorAlarmStatisticsMap', (_message.Message,), dict(

  StatsMapEntry = _reflection.GeneratedProtocolMessageType('StatsMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY,
    __module__ = 'alarm_statistics_pb2'
    # @@protoc_insertion_point(class_scope:Proto3MonitorAlarmStatisticsMap.StatsMapEntry)
    ))
  ,
  DESCRIPTOR = _PROTO3MONITORALARMSTATISTICSMAP,
  __module__ = 'alarm_statistics_pb2'
  # @@protoc_insertion_point(class_scope:Proto3MonitorAlarmStatisticsMap)
  ))
_sym_db.RegisterMessage(Proto3MonitorAlarmStatisticsMap)
_sym_db.RegisterMessage(Proto3MonitorAlarmStatisticsMap.StatsMapEntry)

Proto3AlarmStatisticsMap = _reflection.GeneratedProtocolMessageType('Proto3AlarmStatisticsMap', (_message.Message,), dict(

  StatsMapEntry = _reflection.GeneratedProtocolMessageType('StatsMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY,
    __module__ = 'alarm_statistics_pb2'
    # @@protoc_insertion_point(class_scope:Proto3AlarmStatisticsMap.StatsMapEntry)
    ))
  ,
  DESCRIPTOR = _PROTO3ALARMSTATISTICSMAP,
  __module__ = 'alarm_statistics_pb2'
  # @@protoc_insertion_point(class_scope:Proto3AlarmStatisticsMap)
  ))
_sym_db.RegisterMessage(Proto3AlarmStatisticsMap)
_sym_db.RegisterMessage(Proto3AlarmStatisticsMap.StatsMapEntry)


DESCRIPTOR._options = None
_PROTO3MONITORALARMSTATISTICSSTATIONMAP_INTEGERMAPENTRY._options = None
_PROTO3MONITORALARMSTATISTICSMAP_STATSMAPENTRY._options = None
_PROTO3ALARMSTATISTICSMAP_STATSMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
