# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cfdp_pdu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import abstract_message_pb2 as abstract__message__pb2
import holders_pb2 as holders__pb2
from primitives import time_primitives_pb2 as primitives_dot_time__primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cfdp_pdu.proto',
  package='tm_impl',
  syntax='proto3',
  serialized_options=_b('\n\035jpl.gds.serialization.tm_implB#ProtoBufCfdpPduMessageSerializaitonH\001P\001'),
  serialized_pb=_b('\n\x0e\x63\x66\x64p_pdu.proto\x12\x07tm_impl\x1a\x16\x61\x62stract_message.proto\x1a\rholders.proto\x1a primitives/time_primitives.proto\"\xc1\x05\n\x14Proto3CfdpPduMessage\x12.\n\x05super\x18\x01 \x01(\x0b\x32\x1f.messages.Proto3AbstractMessage\x12\x0f\n\x07pduData\x18\x02 \x01(\x0c\x12\x37\n\x08\x66rameIds\x18\x03 \x01(\x0b\x32#.tm_impl.Proto3CfdpPduMessageFramesH\x00\x12\x30\n\x08packetId\x18\x04 \x01(\x0b\x32\x1c.holder.Proto3PacketIdHolderH\x00\x12\x11\n\tsessionId\x18\x05 \x01(\x03\x12\x0e\n\x06hostId\x18\x06 \x01(\x05\x12\x10\n\x08\x66ragment\x18\x07 \x01(\x05\x12\x13\n\x0bsessionName\x18\x08 \x01(\t\x12\x0c\n\x04host\x18\t \x01(\t\x12\x0c\n\x04user\x18\n \x01(\t\x12\x18\n\x10\x66swDictionaryDir\x18\x0b \x01(\t\x12\x12\n\nfswVersion\x18\x0c \x01(\t\x12\x11\n\tvenueType\x18\r \x01(\t\x12\x13\n\x0btestbedName\x18\x0e \x01(\t\x12\x11\n\toutputDir\x18\x0f \x01(\t\x12\x0c\n\x04scid\x18\x10 \x01(\x05\x12\x0c\n\x04\x61pid\x18\x11 \x01(\x05\x12\x12\n\x08\x61pidName\x18\x12 \x01(\tH\x01\x12\x0c\n\x04vcid\x18\x13 \x01(\x05\x12\x11\n\trelayScid\x18\x14 \x01(\x05\x12\x15\n\rsequenceCount\x18\x15 \x01(\x05\x12\x1b\n\x04sclk\x18\x16 \x01(\x0b\x32\x0b.Proto3SclkH\x02\x12\x19\n\x03lst\x18\x17 \x01(\x0b\x32\n.Proto3LstH\x03\x12\x1a\n\x04scet\x18\x18 \x01(\x0b\x32\n.Proto3AdtH\x04\x12\x17\n\x03\x65rt\x18\x19 \x01(\x0b\x32\n.Proto3Adt\x12\x1a\n\x12simulatorGenerated\x18\x1a \x01(\x08\x42\x0e\n\x0c\x63ontainerIdsB\r\n\x0bhasApidNameB\t\n\x07hasSclkB\x08\n\x06hasLstB\t\n\x07hasScet\"P\n\x1aProto3CfdpPduMessageFrames\x12\x32\n\rsingleFrameId\x18\x01 \x03(\x0b\x32\x1b.holder.Proto3FrameIdHolderBH\n\x1djpl.gds.serialization.tm_implB#ProtoBufCfdpPduMessageSerializaitonH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[abstract__message__pb2.DESCRIPTOR,holders__pb2.DESCRIPTOR,primitives_dot_time__primitives__pb2.DESCRIPTOR,])




_PROTO3CFDPPDUMESSAGE = _descriptor.Descriptor(
  name='Proto3CfdpPduMessage',
  full_name='tm_impl.Proto3CfdpPduMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super', full_name='tm_impl.Proto3CfdpPduMessage.super', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pduData', full_name='tm_impl.Proto3CfdpPduMessage.pduData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frameIds', full_name='tm_impl.Proto3CfdpPduMessage.frameIds', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packetId', full_name='tm_impl.Proto3CfdpPduMessage.packetId', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='tm_impl.Proto3CfdpPduMessage.sessionId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostId', full_name='tm_impl.Proto3CfdpPduMessage.hostId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragment', full_name='tm_impl.Proto3CfdpPduMessage.fragment', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionName', full_name='tm_impl.Proto3CfdpPduMessage.sessionName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='tm_impl.Proto3CfdpPduMessage.host', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='tm_impl.Proto3CfdpPduMessage.user', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fswDictionaryDir', full_name='tm_impl.Proto3CfdpPduMessage.fswDictionaryDir', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fswVersion', full_name='tm_impl.Proto3CfdpPduMessage.fswVersion', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='venueType', full_name='tm_impl.Proto3CfdpPduMessage.venueType', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testbedName', full_name='tm_impl.Proto3CfdpPduMessage.testbedName', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputDir', full_name='tm_impl.Proto3CfdpPduMessage.outputDir', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scid', full_name='tm_impl.Proto3CfdpPduMessage.scid', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apid', full_name='tm_impl.Proto3CfdpPduMessage.apid', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apidName', full_name='tm_impl.Proto3CfdpPduMessage.apidName', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vcid', full_name='tm_impl.Proto3CfdpPduMessage.vcid', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relayScid', full_name='tm_impl.Proto3CfdpPduMessage.relayScid', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequenceCount', full_name='tm_impl.Proto3CfdpPduMessage.sequenceCount', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sclk', full_name='tm_impl.Proto3CfdpPduMessage.sclk', index=21,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lst', full_name='tm_impl.Proto3CfdpPduMessage.lst', index=22,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scet', full_name='tm_impl.Proto3CfdpPduMessage.scet', index=23,
      number=24, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ert', full_name='tm_impl.Proto3CfdpPduMessage.ert', index=24,
      number=25, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simulatorGenerated', full_name='tm_impl.Proto3CfdpPduMessage.simulatorGenerated', index=25,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='containerIds', full_name='tm_impl.Proto3CfdpPduMessage.containerIds',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasApidName', full_name='tm_impl.Proto3CfdpPduMessage.hasApidName',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasSclk', full_name='tm_impl.Proto3CfdpPduMessage.hasSclk',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasLst', full_name='tm_impl.Proto3CfdpPduMessage.hasLst',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='hasScet', full_name='tm_impl.Proto3CfdpPduMessage.hasScet',
      index=4, containing_type=None, fields=[]),
  ],
  serialized_start=101,
  serialized_end=806,
)


_PROTO3CFDPPDUMESSAGEFRAMES = _descriptor.Descriptor(
  name='Proto3CfdpPduMessageFrames',
  full_name='tm_impl.Proto3CfdpPduMessageFrames',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='singleFrameId', full_name='tm_impl.Proto3CfdpPduMessageFrames.singleFrameId', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=808,
  serialized_end=888,
)

_PROTO3CFDPPDUMESSAGE.fields_by_name['super'].message_type = abstract__message__pb2._PROTO3ABSTRACTMESSAGE
_PROTO3CFDPPDUMESSAGE.fields_by_name['frameIds'].message_type = _PROTO3CFDPPDUMESSAGEFRAMES
_PROTO3CFDPPDUMESSAGE.fields_by_name['packetId'].message_type = holders__pb2._PROTO3PACKETIDHOLDER
_PROTO3CFDPPDUMESSAGE.fields_by_name['sclk'].message_type = primitives_dot_time__primitives__pb2._PROTO3SCLK
_PROTO3CFDPPDUMESSAGE.fields_by_name['lst'].message_type = primitives_dot_time__primitives__pb2._PROTO3LST
_PROTO3CFDPPDUMESSAGE.fields_by_name['scet'].message_type = primitives_dot_time__primitives__pb2._PROTO3ADT
_PROTO3CFDPPDUMESSAGE.fields_by_name['ert'].message_type = primitives_dot_time__primitives__pb2._PROTO3ADT
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['containerIds'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['frameIds'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['frameIds'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['containerIds']
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['containerIds'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['packetId'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['packetId'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['containerIds']
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasApidName'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['apidName'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['apidName'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasApidName']
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasSclk'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['sclk'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['sclk'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasSclk']
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasLst'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['lst'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['lst'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasLst']
_PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasScet'].fields.append(
  _PROTO3CFDPPDUMESSAGE.fields_by_name['scet'])
_PROTO3CFDPPDUMESSAGE.fields_by_name['scet'].containing_oneof = _PROTO3CFDPPDUMESSAGE.oneofs_by_name['hasScet']
_PROTO3CFDPPDUMESSAGEFRAMES.fields_by_name['singleFrameId'].message_type = holders__pb2._PROTO3FRAMEIDHOLDER
DESCRIPTOR.message_types_by_name['Proto3CfdpPduMessage'] = _PROTO3CFDPPDUMESSAGE
DESCRIPTOR.message_types_by_name['Proto3CfdpPduMessageFrames'] = _PROTO3CFDPPDUMESSAGEFRAMES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3CfdpPduMessage = _reflection.GeneratedProtocolMessageType('Proto3CfdpPduMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3CFDPPDUMESSAGE,
  __module__ = 'cfdp_pdu_pb2'
  # @@protoc_insertion_point(class_scope:tm_impl.Proto3CfdpPduMessage)
  ))
_sym_db.RegisterMessage(Proto3CfdpPduMessage)

Proto3CfdpPduMessageFrames = _reflection.GeneratedProtocolMessageType('Proto3CfdpPduMessageFrames', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3CFDPPDUMESSAGEFRAMES,
  __module__ = 'cfdp_pdu_pb2'
  # @@protoc_insertion_point(class_scope:tm_impl.Proto3CfdpPduMessageFrames)
  ))
_sym_db.RegisterMessage(Proto3CfdpPduMessageFrames)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
