# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: holders.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitives import holder_primitives_pb2 as primitives_dot_holder__primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='holders.proto',
  package='holder',
  syntax='proto3',
  serialized_options=_b('\n\034jpl.gds.serialization.holderB\033ProtoBufHolderSerializationH\001P\001'),
  serialized_pb=_b('\n\rholders.proto\x12\x06holder\x1a\"primitives/holder_primitives.proto\"B\n\x12Proto3HeaderHolder\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.holder.Proto3AbstractHolder\"D\n\x13Proto3TrailerHolder\x12-\n\x07trailer\x18\x01 \x01(\x0b\x32\x1c.holder.Proto3AbstractHolder\"F\n\x14Proto3PacketIdHolder\x12.\n\x08packetId\x18\x01 \x01(\x0b\x32\x1c.holder.Proto3AbstractHolder\"D\n\x13Proto3FrameIdHolder\x12-\n\x07\x66rameId\x18\x01 \x01(\x0b\x32\x1c.holder.Proto3AbstractHolderB?\n\x1cjpl.gds.serialization.holderB\x1bProtoBufHolderSerializationH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[primitives_dot_holder__primitives__pb2.DESCRIPTOR,])




_PROTO3HEADERHOLDER = _descriptor.Descriptor(
  name='Proto3HeaderHolder',
  full_name='holder.Proto3HeaderHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='holder.Proto3HeaderHolder.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=127,
)


_PROTO3TRAILERHOLDER = _descriptor.Descriptor(
  name='Proto3TrailerHolder',
  full_name='holder.Proto3TrailerHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trailer', full_name='holder.Proto3TrailerHolder.trailer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=197,
)


_PROTO3PACKETIDHOLDER = _descriptor.Descriptor(
  name='Proto3PacketIdHolder',
  full_name='holder.Proto3PacketIdHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetId', full_name='holder.Proto3PacketIdHolder.packetId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=269,
)


_PROTO3FRAMEIDHOLDER = _descriptor.Descriptor(
  name='Proto3FrameIdHolder',
  full_name='holder.Proto3FrameIdHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='holder.Proto3FrameIdHolder.frameId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=339,
)

_PROTO3HEADERHOLDER.fields_by_name['header'].message_type = primitives_dot_holder__primitives__pb2._PROTO3ABSTRACTHOLDER
_PROTO3TRAILERHOLDER.fields_by_name['trailer'].message_type = primitives_dot_holder__primitives__pb2._PROTO3ABSTRACTHOLDER
_PROTO3PACKETIDHOLDER.fields_by_name['packetId'].message_type = primitives_dot_holder__primitives__pb2._PROTO3ABSTRACTHOLDER
_PROTO3FRAMEIDHOLDER.fields_by_name['frameId'].message_type = primitives_dot_holder__primitives__pb2._PROTO3ABSTRACTHOLDER
DESCRIPTOR.message_types_by_name['Proto3HeaderHolder'] = _PROTO3HEADERHOLDER
DESCRIPTOR.message_types_by_name['Proto3TrailerHolder'] = _PROTO3TRAILERHOLDER
DESCRIPTOR.message_types_by_name['Proto3PacketIdHolder'] = _PROTO3PACKETIDHOLDER
DESCRIPTOR.message_types_by_name['Proto3FrameIdHolder'] = _PROTO3FRAMEIDHOLDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3HeaderHolder = _reflection.GeneratedProtocolMessageType('Proto3HeaderHolder', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3HEADERHOLDER,
  __module__ = 'holders_pb2'
  # @@protoc_insertion_point(class_scope:holder.Proto3HeaderHolder)
  ))
_sym_db.RegisterMessage(Proto3HeaderHolder)

Proto3TrailerHolder = _reflection.GeneratedProtocolMessageType('Proto3TrailerHolder', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3TRAILERHOLDER,
  __module__ = 'holders_pb2'
  # @@protoc_insertion_point(class_scope:holder.Proto3TrailerHolder)
  ))
_sym_db.RegisterMessage(Proto3TrailerHolder)

Proto3PacketIdHolder = _reflection.GeneratedProtocolMessageType('Proto3PacketIdHolder', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3PACKETIDHOLDER,
  __module__ = 'holders_pb2'
  # @@protoc_insertion_point(class_scope:holder.Proto3PacketIdHolder)
  ))
_sym_db.RegisterMessage(Proto3PacketIdHolder)

Proto3FrameIdHolder = _reflection.GeneratedProtocolMessageType('Proto3FrameIdHolder', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3FRAMEIDHOLDER,
  __module__ = 'holders_pb2'
  # @@protoc_insertion_point(class_scope:holder.Proto3FrameIdHolder)
  ))
_sym_db.RegisterMessage(Proto3FrameIdHolder)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
