# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import metadata_map_pb2 as metadata__map__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_block.proto',
  package='transport',
  syntax='proto3',
  serialized_options=_b('\n\033jpl.gds.serialization.blockB\024ProtoBufMessageBlockH\001P\001'),
  serialized_pb=_b('\n\x13message_block.proto\x12\ttransport\x1a\x12metadata_map.proto\"W\n\x12Proto3MessageBlock\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.metadata.Proto3MetadataMap\x12\x14\n\x0cmessageBytes\x18\x02 \x03(\x0c\x42\x37\n\x1bjpl.gds.serialization.blockB\x14ProtoBufMessageBlockH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[metadata__map__pb2.DESCRIPTOR,])




_PROTO3MESSAGEBLOCK = _descriptor.Descriptor(
  name='Proto3MessageBlock',
  full_name='transport.Proto3MessageBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='transport.Proto3MessageBlock.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageBytes', full_name='transport.Proto3MessageBlock.messageBytes', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=141,
)

_PROTO3MESSAGEBLOCK.fields_by_name['header'].message_type = metadata__map__pb2._PROTO3METADATAMAP
DESCRIPTOR.message_types_by_name['Proto3MessageBlock'] = _PROTO3MESSAGEBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3MessageBlock = _reflection.GeneratedProtocolMessageType('Proto3MessageBlock', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3MESSAGEBLOCK,
  __module__ = 'message_block_pb2'
  # @@protoc_insertion_point(class_scope:transport.Proto3MessageBlock)
  ))
_sym_db.RegisterMessage(Proto3MessageBlock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
