# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import abstract_message_pb2 as abstract__message__pb2
import holders_pb2 as holders__pb2
import station_info_pb2 as station__info__pb2
import frame_info_pb2 as frame__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry_frame.proto',
  package='frame',
  syntax='proto3',
  serialized_options=_b('\n\033jpl.gds.serialization.frameB*ProtoBufTelemetryFrameMessageSerializationH\001P\001'),
  serialized_pb=_b('\n\x15telemetry_frame.proto\x12\x05\x66rame\x1a\x16\x61\x62stract_message.proto\x1a\rholders.proto\x1a\x12station_info.proto\x1a\x10\x66rame_info.proto\"\x96\x02\n\x1bProto3TelemetryFrameMessage\x12.\n\x05super\x18\x01 \x01(\x0b\x32\x1f.messages.Proto3AbstractMessage\x12\x30\n\x07\x64snInfo\x18\x02 \x01(\x0b\x32\x1f.station.Proto3StationTelemInfo\x12/\n\x06tfInfo\x18\x03 \x01(\x0b\x32\x1f.frame.Proto3TelemetryFrameInfo\x12\n\n\x02tf\x18\x04 \x01(\x0c\x12*\n\x06header\x18\x05 \x01(\x0b\x32\x1a.holder.Proto3HeaderHolder\x12,\n\x07trailer\x18\x06 \x01(\x0b\x32\x1b.holder.Proto3TrailerHolderBM\n\x1bjpl.gds.serialization.frameB*ProtoBufTelemetryFrameMessageSerializationH\x01P\x01\x62\x06proto3')
  ,
  dependencies=[abstract__message__pb2.DESCRIPTOR,holders__pb2.DESCRIPTOR,station__info__pb2.DESCRIPTOR,frame__info__pb2.DESCRIPTOR,])




_PROTO3TELEMETRYFRAMEMESSAGE = _descriptor.Descriptor(
  name='Proto3TelemetryFrameMessage',
  full_name='frame.Proto3TelemetryFrameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super', full_name='frame.Proto3TelemetryFrameMessage.super', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dsnInfo', full_name='frame.Proto3TelemetryFrameMessage.dsnInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tfInfo', full_name='frame.Proto3TelemetryFrameMessage.tfInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tf', full_name='frame.Proto3TelemetryFrameMessage.tf', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='frame.Proto3TelemetryFrameMessage.header', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trailer', full_name='frame.Proto3TelemetryFrameMessage.trailer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=388,
)

_PROTO3TELEMETRYFRAMEMESSAGE.fields_by_name['super'].message_type = abstract__message__pb2._PROTO3ABSTRACTMESSAGE
_PROTO3TELEMETRYFRAMEMESSAGE.fields_by_name['dsnInfo'].message_type = station__info__pb2._PROTO3STATIONTELEMINFO
_PROTO3TELEMETRYFRAMEMESSAGE.fields_by_name['tfInfo'].message_type = frame__info__pb2._PROTO3TELEMETRYFRAMEINFO
_PROTO3TELEMETRYFRAMEMESSAGE.fields_by_name['header'].message_type = holders__pb2._PROTO3HEADERHOLDER
_PROTO3TELEMETRYFRAMEMESSAGE.fields_by_name['trailer'].message_type = holders__pb2._PROTO3TRAILERHOLDER
DESCRIPTOR.message_types_by_name['Proto3TelemetryFrameMessage'] = _PROTO3TELEMETRYFRAMEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3TelemetryFrameMessage = _reflection.GeneratedProtocolMessageType('Proto3TelemetryFrameMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3TELEMETRYFRAMEMESSAGE,
  __module__ = 'telemetry_frame_pb2'
  # @@protoc_insertion_point(class_scope:frame.Proto3TelemetryFrameMessage)
  ))
_sym_db.RegisterMessage(Proto3TelemetryFrameMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
