/*
 * Copyright 2006-2018. California Institute of Technology.
 * ALL RIGHTS RESERVED.
 * U.S. Government sponsorship acknowledged.
 *
 * This software is subject to U. S. export control laws and
 * regulations (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the
 * extent that the software is subject to U.S. export control laws
 * and regulations, the recipient has the responsibility to obtain
 * export licenses or other export authority as may be required
 * before exporting such information to foreign countries or
 * providing access to foreign nationals.
 */
package jpl.gds.db.api.types;

/**
 * Generic implementation of an IDbQueryable Factory
 * 
 * @param <T>
 *            the Type of IDbQueryable Provider generated by this factory
 * @param <Q>
 *            the Type of IDbQueryable Updater generated by this factory
 */
public interface IDbQueryableFactory<T extends IDbInfoProvider, Q extends T> {
    /**
     * 
     */
    public static final String DB_CHANNEL_SAMPLE_FACTORY   = "DB_CHANNEL_SAMPLE_FACTORY";

    /**
     * 
     */
    public static final String DB_EVR_FACTORY              = "DB_EVR_FACTORY";

    /**
     * 
     */
    public static final String DB_COMMAND_FACTORY          = "DB_COMMAND_FACTORY";

    /**
     * 
     */
    public static final String DB_PRODUCT_METADATA_FACTORY = "DB_PRODUCT_METADATA_FACTORY";

    /**
     * 
     */
    public static final String DB_LOG_FACTORY              = "DB_LOG_FACTORY";

    /**
     * 
     */
    public static final String DB_1553_LOG_FACTORY         = "DB_1553_LOG_FACTORY";

    /**
     * 
     */
    public static final String DB_CHANNEL_METADATA_FACTORY = "DB_CHANNEL_METADATA_FACTORY";

    /**
     * 
     */
    public static final String DB_END_SESSION_FACTORY      = "DB_END_SESSION_FACTORY";

    /**
     * 
     */
    public static final String DB_FRAME_FACTORY            = "DB_FRAME_FACTORY";

    /**
     * 
     */
    public static final String DB_PACKET_FACTORY           = "DB_PACKET_FACTORY";

    /**
     * 
     */
    public static final String DB_SESSION_FACTORY          = "DB_SESSION_FACTORY";

    /**
     * 
     */
    public static final String DB_SESSION_INFO_FACTORY     = "DB_SESSION_INFO_FACTORY";

    /**
     *
     */
    public static final String DB_CONTEXT_CONFIG_FACTORY     = "DB_CONTEXT_CONFIG_FACTORY";

    /**
     *
     */
    public static final String DB_CONTEXT_INFO_FACTORY     = "DB_CONTEXT_INFO_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_INDICATION_FACTORY           = "DB_CFDP_INDICATION_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_FILE_GENERATION_FACTORY           = "DB_CFDP_FILE_GENERATION_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_FILE_UPLINK_FINISHED_FACTORY           = "DB_CFDP_FILE_UPLINK_FINISHED_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_REQUEST_RECEIVED_FACTORY           = "DB_CFDP_REQUEST_RECEIVED_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_REQUEST_RESULT_FACTORY           = "DB_CFDP_REQUEST_RESULT_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_PDU_RECEIVED_FACTORY           = "DB_CFDP_PDU_RECEIVED_FACTORY";

    /**
     * 
     */
    public static final String DB_CFDP_PDU_SENT_FACTORY           = "DB_CFDP_PDU_SENT_FACTORY";

    /**
     * 
     */
    public static final String AGGREGATE_FETCH_CONFIG      = "AGGREGATE_FETCH_CONFIG";
    
    /**
     * 
     */
    public static final String BATCH_READER_FACTORY        = "BATCH_READER_FACTORY";
    
    /**
     * 
     */
    public static final String INDEX_READER_FACTORY        = "INDEX_READER_FACTORY";    
    
    /**
     * 
     */
    public static final String BATCH_WRITER_FACTORY        = "BATCH_WRITER_FACTORY";
    
    /**
     * 
     */
    public static final String BATCH_MERGE_FACTORY         = "BATCH_MERGE_FACTORY";
    
    /**
     * 
     */
    public static final String BATCH_PROCESSOR_FACTORY     = "BATCH_PROCESSOR_FACTORY";
    
    /**
     * 
     */
    public static final String EHA_AGGREGATE_QUERY_COORDINATOR     = "EHA_AGGREGATE_QUERY_COORDINATOR";    
    
    /**
     * @return an IDbQueryable object
     */
    T createQueryableProvider();

    /**
     * @param args
     *            optional arguments to underlying object's constructor
     * @return an IDbQueryable object
     */
    T createQueryableProvider(Object... args);

    /**
     * @return an IDbProductMetadataProvider object instantiated with no data
     */
    Q createQueryableUpdater();

    /**
     * @param args
     *            optional arguments to underlying object's constructor
     * @return an IDbProductMetadataProvider object instantiated with no data
     */
    Q createQueryableUpdater(Object... args);

    /**
     * Converts a compatible IDbProductMetadataProvider to an
     * IDbSessionInfoUpdater.
     * 
     * @param provider
     *            the object to cast
     * 
     * @return the re-cast T reference to an Q
     */
    public Q convertProviderToUpdater(final T provider);
}