/*
 * Copyright 2006-2018. California Institute of Technology.
 * ALL RIGHTS RESERVED.
 * U.S. Government sponsorship acknowledged.
 *
 * This software is subject to U. S. export control laws and
 * regulations (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the
 * extent that the software is subject to U.S. export control laws
 * and regulations, the recipient has the responsibility to obtain
 * export licenses or other export authority as may be required
 * before exporting such information to foreign countries or
 * providing access to foreign nationals.
 */
package ammos.datagen.mission.nsyt.generators;

import ammos.datagen.generators.util.UsageTracker;
import ammos.datagen.generators.util.UsageTrackerMap;

/**
 * ContinuousUsageTrackerMap extends the general UsageTrackerMap class, which
 * allows it to report information for trackers unique to NSYT continuous packet
 * generation.
 * 
 * @see ammos.datagen.generators.util.UsageTrackerMap
 * 
 * MPCS-6864 - 12/2/14. Added class.
 */
public class ContinuousUsageTrackerMap extends UsageTrackerMap {

	/**
	 * {@inheritDoc}
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {

		final StringBuilder sb = new StringBuilder(super.toString());

		/*
		 * Append info for NSYT continuous-specific trackers to the String
		 * generated by the super class.
		 */
		for (final ContinuousTrackerType t : ContinuousTrackerType.values()) {
			final UsageTracker ut = this.trackers.get(t.getMapType());
			if (ut == null) {
				continue;
			}
			sb.append("  " + t.getDisplayName() + ": "
					+ String.format("%.1f", ut.getPercentFilled()) + "%\n");
		}
		return sb.toString();

	}
}
