# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/alarm_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/alarm_primitives.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n&jpl.gds.serialization.primitives.alarmB#ProtoBufAlarmPrimitiveSerializationH\001P\001'),
  serialized_pb=_b('\n!primitives/alarm_primitives.proto*1\n\x10Proto3AlarmLevel\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x07\n\x03RED\x10\x02*\xa7\x02\n\x0fProto3AlarmType\x12\x0b\n\x07NO_TYPE\x10\x00\x12\x16\n\x12HIGH_VALUE_COMPARE\x10\x01\x12\x15\n\x11LOW_VALUE_COMPARE\x10\x02\x12\x11\n\rSTATE_COMPARE\x10\x03\x12\x10\n\x0cVALUE_CHANGE\x10\x04\x12\x0f\n\x0bVALUE_DELTA\x10\x05\x12\x15\n\x11\x45XCLUSIVE_COMPARE\x10\x06\x12\x15\n\x11INCLUSIVE_COMPARE\x10\x07\x12\x13\n\x0f\x44IGITAL_COMPARE\x10\x08\x12\x10\n\x0cMASK_COMPARE\x10\t\x12\x0c\n\x08\x43OMPOUND\x10\n\x12\x0f\n\x0b\x43OMBINATION\x10\x0b\x12\x16\n\x12\x43OMBINATION_SOURCE\x10\x0c\x12\x16\n\x12\x43OMBINATION_TARGET\x10\rBQ\n&jpl.gds.serialization.primitives.alarmB#ProtoBufAlarmPrimitiveSerializationH\x01P\x01\x62\x06proto3')
)

_PROTO3ALARMLEVEL = _descriptor.EnumDescriptor(
  name='Proto3AlarmLevel',
  full_name='Proto3AlarmLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=37,
  serialized_end=86,
)
_sym_db.RegisterEnumDescriptor(_PROTO3ALARMLEVEL)

Proto3AlarmLevel = enum_type_wrapper.EnumTypeWrapper(_PROTO3ALARMLEVEL)
_PROTO3ALARMTYPE = _descriptor.EnumDescriptor(
  name='Proto3AlarmType',
  full_name='Proto3AlarmType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_VALUE_COMPARE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW_VALUE_COMPARE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_COMPARE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_CHANGE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_DELTA', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCLUSIVE_COMPARE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCLUSIVE_COMPARE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_COMPARE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASK_COMPARE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPOUND', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMBINATION', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMBINATION_SOURCE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMBINATION_TARGET', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=89,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_PROTO3ALARMTYPE)

Proto3AlarmType = enum_type_wrapper.EnumTypeWrapper(_PROTO3ALARMTYPE)
NONE = 0
YELLOW = 1
RED = 2
NO_TYPE = 0
HIGH_VALUE_COMPARE = 1
LOW_VALUE_COMPARE = 2
STATE_COMPARE = 3
VALUE_CHANGE = 4
VALUE_DELTA = 5
EXCLUSIVE_COMPARE = 6
INCLUSIVE_COMPARE = 7
DIGITAL_COMPARE = 8
MASK_COMPARE = 9
COMPOUND = 10
COMBINATION = 11
COMBINATION_SOURCE = 12
COMBINATION_TARGET = 13


DESCRIPTOR.enum_types_by_name['Proto3AlarmLevel'] = _PROTO3ALARMLEVEL
DESCRIPTOR.enum_types_by_name['Proto3AlarmType'] = _PROTO3ALARMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
