# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/eha_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/eha_primitives.proto',
  package='eha',
  syntax='proto3',
  serialized_options=_b('\n%jpl.gds.eha.api.channel.serializationB!ProtoBufEhaPrimitiveSerializationH\001P\001'),
  serialized_pb=_b('\n\x1fprimitives/eha_primitives.proto\x12\x03\x65ha\"\xbe\x01\n\x08Proto3Dn\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.eha.Proto3DnType\x12\x10\n\x06_float\x18\x02 \x01(\x02H\x00\x12\x11\n\x07_double\x18\x03 \x01(\x01H\x00\x12\x0e\n\x04_int\x18\x04 \x01(\x05H\x00\x12\x0f\n\x05_uint\x18\x05 \x01(\rH\x00\x12\x0f\n\x05_long\x18\x06 \x01(\x03H\x00\x12\x10\n\x06_ulong\x18\x07 \x01(\x04H\x00\x12\x0f\n\x05_bool\x18\x08 \x01(\x08H\x00\x12\x11\n\x07_string\x18\t \x01(\tH\x00\x42\x04\n\x02\x64n*\xcb\x01\n\x0cProto3DnType\x12\x13\n\x0f\x44N_TYPE_UNKNOWN\x10\x00\x12\x16\n\x12\x44N_TYPE_SIGNED_INT\x10\x01\x12\x18\n\x14\x44N_TYPE_UNSIGNED_INT\x10\x02\x12\x13\n\x0f\x44N_TYPE_DIGITAL\x10\x03\x12\x12\n\x0e\x44N_TYPE_STATUS\x10\x04\x12\x11\n\rDN_TYPE_FLOAT\x10\x05\x12\x11\n\rDN_TYPE_ASCII\x10\x06\x12\x13\n\x0f\x44N_TYPE_BOOLEAN\x10\x07\x12\x10\n\x0c\x44N_TYPE_TIME\x10\x08*\x86\x01\n\x11Proto3ChanDefType\x12\x19\n\x15\x43HAN_DEF_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11\x43HAN_DEF_TYPE_FSW\x10\x01\x12\x15\n\x11\x43HAN_DEF_TYPE_SSE\x10\x02\x12\x13\n\x0f\x43HAN_DEF_TYPE_M\x10\x03\x12\x13\n\x0f\x43HAN_DEF_TYPE_H\x10\x04\x42N\n%jpl.gds.eha.api.channel.serializationB!ProtoBufEhaPrimitiveSerializationH\x01P\x01\x62\x06proto3')
)

_PROTO3DNTYPE = _descriptor.EnumDescriptor(
  name='Proto3DnType',
  full_name='eha.Proto3DnType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_SIGNED_INT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_UNSIGNED_INT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_DIGITAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_STATUS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_FLOAT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_ASCII', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_BOOLEAN', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DN_TYPE_TIME', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=234,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_PROTO3DNTYPE)

Proto3DnType = enum_type_wrapper.EnumTypeWrapper(_PROTO3DNTYPE)
_PROTO3CHANDEFTYPE = _descriptor.EnumDescriptor(
  name='Proto3ChanDefType',
  full_name='eha.Proto3ChanDefType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAN_DEF_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAN_DEF_TYPE_FSW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAN_DEF_TYPE_SSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAN_DEF_TYPE_M', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAN_DEF_TYPE_H', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=440,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_PROTO3CHANDEFTYPE)

Proto3ChanDefType = enum_type_wrapper.EnumTypeWrapper(_PROTO3CHANDEFTYPE)
DN_TYPE_UNKNOWN = 0
DN_TYPE_SIGNED_INT = 1
DN_TYPE_UNSIGNED_INT = 2
DN_TYPE_DIGITAL = 3
DN_TYPE_STATUS = 4
DN_TYPE_FLOAT = 5
DN_TYPE_ASCII = 6
DN_TYPE_BOOLEAN = 7
DN_TYPE_TIME = 8
CHAN_DEF_TYPE_UNKNOWN = 0
CHAN_DEF_TYPE_FSW = 1
CHAN_DEF_TYPE_SSE = 2
CHAN_DEF_TYPE_M = 3
CHAN_DEF_TYPE_H = 4



_PROTO3DN = _descriptor.Descriptor(
  name='Proto3Dn',
  full_name='eha.Proto3Dn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='eha.Proto3Dn.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_float', full_name='eha.Proto3Dn._float', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_double', full_name='eha.Proto3Dn._double', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_int', full_name='eha.Proto3Dn._int', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_uint', full_name='eha.Proto3Dn._uint', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_long', full_name='eha.Proto3Dn._long', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_ulong', full_name='eha.Proto3Dn._ulong', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_bool', full_name='eha.Proto3Dn._bool', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_string', full_name='eha.Proto3Dn._string', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='dn', full_name='eha.Proto3Dn.dn',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=41,
  serialized_end=231,
)

_PROTO3DN.fields_by_name['type'].enum_type = _PROTO3DNTYPE
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_float'])
_PROTO3DN.fields_by_name['_float'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_double'])
_PROTO3DN.fields_by_name['_double'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_int'])
_PROTO3DN.fields_by_name['_int'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_uint'])
_PROTO3DN.fields_by_name['_uint'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_long'])
_PROTO3DN.fields_by_name['_long'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_ulong'])
_PROTO3DN.fields_by_name['_ulong'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_bool'])
_PROTO3DN.fields_by_name['_bool'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
_PROTO3DN.oneofs_by_name['dn'].fields.append(
  _PROTO3DN.fields_by_name['_string'])
_PROTO3DN.fields_by_name['_string'].containing_oneof = _PROTO3DN.oneofs_by_name['dn']
DESCRIPTOR.message_types_by_name['Proto3Dn'] = _PROTO3DN
DESCRIPTOR.enum_types_by_name['Proto3DnType'] = _PROTO3DNTYPE
DESCRIPTOR.enum_types_by_name['Proto3ChanDefType'] = _PROTO3CHANDEFTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3Dn = _reflection.GeneratedProtocolMessageType('Proto3Dn', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3DN,
  __module__ = 'primitives.eha_primitives_pb2'
  # @@protoc_insertion_point(class_scope:eha.Proto3Dn)
  ))
_sym_db.RegisterMessage(Proto3Dn)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
