# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/holder_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/holder_primitives.proto',
  package='holder',
  syntax='proto3',
  serialized_options=_b('\n\'jpl.gds.serialization.primitives.holderB$ProtoBufHolderPrimitiveSerializationH\001P\001'),
  serialized_pb=_b('\n\"primitives/holder_primitives.proto\x12\x06holder\"x\n\x14Proto3AbstractHolder\x12\x15\n\risUnspecified\x18\x01 \x01(\x08\x12\x15\n\risUnsupported\x18\x02 \x01(\x08\x12\x14\n\nbytesValue\x18\x03 \x01(\x0cH\x00\x12\x13\n\tlongValue\x18\x04 \x01(\x04H\x00\x42\x07\n\x05valueBS\n\'jpl.gds.serialization.primitives.holderB$ProtoBufHolderPrimitiveSerializationH\x01P\x01\x62\x06proto3')
)




_PROTO3ABSTRACTHOLDER = _descriptor.Descriptor(
  name='Proto3AbstractHolder',
  full_name='holder.Proto3AbstractHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isUnspecified', full_name='holder.Proto3AbstractHolder.isUnspecified', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isUnsupported', full_name='holder.Proto3AbstractHolder.isUnsupported', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytesValue', full_name='holder.Proto3AbstractHolder.bytesValue', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longValue', full_name='holder.Proto3AbstractHolder.longValue', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='holder.Proto3AbstractHolder.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=46,
  serialized_end=166,
)

_PROTO3ABSTRACTHOLDER.oneofs_by_name['value'].fields.append(
  _PROTO3ABSTRACTHOLDER.fields_by_name['bytesValue'])
_PROTO3ABSTRACTHOLDER.fields_by_name['bytesValue'].containing_oneof = _PROTO3ABSTRACTHOLDER.oneofs_by_name['value']
_PROTO3ABSTRACTHOLDER.oneofs_by_name['value'].fields.append(
  _PROTO3ABSTRACTHOLDER.fields_by_name['longValue'])
_PROTO3ABSTRACTHOLDER.fields_by_name['longValue'].containing_oneof = _PROTO3ABSTRACTHOLDER.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Proto3AbstractHolder'] = _PROTO3ABSTRACTHOLDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3AbstractHolder = _reflection.GeneratedProtocolMessageType('Proto3AbstractHolder', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ABSTRACTHOLDER,
  __module__ = 'primitives.holder_primitives_pb2'
  # @@protoc_insertion_point(class_scope:holder.Proto3AbstractHolder)
  ))
_sym_db.RegisterMessage(Proto3AbstractHolder)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
