# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/key_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/key_value.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n)jpl.gds.serialization.primitives.keyvalueB\035ProtoBufKeyValueSerializationP\001'),
  serialized_pb=_b('\n\x1aprimitives/key_value.proto\"x\n\x0eProto3KeyValue\x12\x33\n\nattributes\x18\x01 \x03(\x0b\x32\x1f.Proto3KeyValue.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42L\n)jpl.gds.serialization.primitives.keyvalueB\x1dProtoBufKeyValueSerializationP\x01\x62\x06proto3')
)




_PROTO3KEYVALUE_ATTRIBUTESENTRY = _descriptor.Descriptor(
  name='AttributesEntry',
  full_name='Proto3KeyValue.AttributesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto3KeyValue.AttributesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3KeyValue.AttributesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=150,
)

_PROTO3KEYVALUE = _descriptor.Descriptor(
  name='Proto3KeyValue',
  full_name='Proto3KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='Proto3KeyValue.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTO3KEYVALUE_ATTRIBUTESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=150,
)

_PROTO3KEYVALUE_ATTRIBUTESENTRY.containing_type = _PROTO3KEYVALUE
_PROTO3KEYVALUE.fields_by_name['attributes'].message_type = _PROTO3KEYVALUE_ATTRIBUTESENTRY
DESCRIPTOR.message_types_by_name['Proto3KeyValue'] = _PROTO3KEYVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3KeyValue = _reflection.GeneratedProtocolMessageType('Proto3KeyValue', (_message.Message,), dict(

  AttributesEntry = _reflection.GeneratedProtocolMessageType('AttributesEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTO3KEYVALUE_ATTRIBUTESENTRY,
    __module__ = 'primitives.key_value_pb2'
    # @@protoc_insertion_point(class_scope:Proto3KeyValue.AttributesEntry)
    ))
  ,
  DESCRIPTOR = _PROTO3KEYVALUE,
  __module__ = 'primitives.key_value_pb2'
  # @@protoc_insertion_point(class_scope:Proto3KeyValue)
  ))
_sym_db.RegisterMessage(Proto3KeyValue)
_sym_db.RegisterMessage(Proto3KeyValue.AttributesEntry)


DESCRIPTOR._options = None
_PROTO3KEYVALUE_ATTRIBUTESENTRY._options = None
# @@protoc_insertion_point(module_scope)
