# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/metadata_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/metadata_primitives.proto',
  package='metadata',
  syntax='proto3',
  serialized_options=_b('\n)jpl.gds.serialization.primitives.metadataB$ProtoMetadataMapElementSerializationH\001P\001'),
  serialized_pb=_b('\n$primitives/metadata_primitives.proto\x12\x08metadata\"\x8e\x02\n\x18Proto3MetadataMapElement\x12(\n\x03key\x18\x01 \x01(\x0e\x32\x1b.metadata.Proto3MetadataKey\x12\x13\n\tboolValue\x18\x02 \x01(\x08H\x00\x12\x15\n\x0bnumberValue\x18\x03 \x01(\x05H\x00\x12\x13\n\tlongValue\x18\x04 \x01(\x03H\x00\x12\x15\n\x0b\x64oubleValue\x18\x05 \x01(\x01H\x00\x12\x14\n\nfloatValue\x18\x06 \x01(\x02H\x00\x12\x15\n\x0bstringValue\x18\x07 \x01(\tH\x00\x12\x1d\n\x13unsignedNumberValue\x18\x08 \x01(\rH\x00\x12\x1b\n\x11unsignedLongValue\x18\t \x01(\x04H\x00\x42\x07\n\x05value*\xcd\x04\n\x11Proto3MetadataKey\x12\x0e\n\nCONTEXT_ID\x10\x00\x12\x14\n\x10\x43ONTEXT_FRAGMENT\x10\x01\x12\x10\n\x0c\x43ONTEXT_HOST\x10\x02\x12\x13\n\x0f\x43ONTEXT_HOST_ID\x10\x03\x12\x12\n\x0e\x43ONTEXT_NUMBER\x10\x04\x12\x10\n\x0c\x43ONTEXT_USER\x10\x05\x12 \n\x1c\x41PPLICATION_OUTPUT_DIRECTORY\x10\x06\x12\x1a\n\x16\x41PPLICATION_ROOT_TOPIC\x10\x07\x12\x14\n\x10\x43ONFIGURED_DSSID\x10\x08\x12\x13\n\x0f\x43ONFIGURED_VCID\x10\t\x12\x0f\n\x0b\x43REATE_TIME\x10\n\x12\x16\n\x12\x46SW_DICTIONARY_DIR\x10\x0b\x12\x1a\n\x16\x46SW_DICTIONARY_VERSION\x10\x0c\x12\x13\n\x0fMESSAGE_COUNTER\x10\r\x12\x10\n\x0cMESSAGE_TYPE\x10\x0e\x12\x0e\n\nMISSION_ID\x10\x0f\x12\x10\n\x0cMISSION_NAME\x10\x10\x12\x12\n\x0ePERSPECTIVE_ID\x10\x11\x12\x0e\n\nSOURCE_PID\x10\x12\x12\x11\n\rSPACECRAFT_ID\x10\x13\x12\x13\n\x0fSPACECRAFT_NAME\x10\x14\x12\x16\n\x12SSE_DICTIONARY_DIR\x10\x15\x12\x1a\n\x16SSE_DICTIONARY_VERSION\x10\x16\x12\x19\n\x15TELEMETRY_STREAM_TYPE\x10\x17\x12\x10\n\x0cTESTBED_NAME\x10\x18\x12\x0e\n\nVENUE_TYPE\x10\x19\x12\x11\n\rAMPCS_VERSION\x10\x1a\x42U\n)jpl.gds.serialization.primitives.metadataB$ProtoMetadataMapElementSerializationH\x01P\x01\x62\x06proto3')
)

_PROTO3METADATAKEY = _descriptor.EnumDescriptor(
  name='Proto3MetadataKey',
  full_name='metadata.Proto3MetadataKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_ID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_FRAGMENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_HOST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_HOST_ID', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_NUMBER', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_USER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLICATION_OUTPUT_DIRECTORY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLICATION_ROOT_TOPIC', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIGURED_DSSID', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIGURED_VCID', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_TIME', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FSW_DICTIONARY_DIR', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FSW_DICTIONARY_VERSION', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_COUNTER', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_TYPE', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_ID', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_NAME', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERSPECTIVE_ID', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOURCE_PID', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPACECRAFT_ID', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPACECRAFT_NAME', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SSE_DICTIONARY_DIR', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SSE_DICTIONARY_VERSION', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TELEMETRY_STREAM_TYPE', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TESTBED_NAME', index=24, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VENUE_TYPE', index=25, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AMPCS_VERSION', index=26, number=26,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=324,
  serialized_end=913,
)
_sym_db.RegisterEnumDescriptor(_PROTO3METADATAKEY)

Proto3MetadataKey = enum_type_wrapper.EnumTypeWrapper(_PROTO3METADATAKEY)
CONTEXT_ID = 0
CONTEXT_FRAGMENT = 1
CONTEXT_HOST = 2
CONTEXT_HOST_ID = 3
CONTEXT_NUMBER = 4
CONTEXT_USER = 5
APPLICATION_OUTPUT_DIRECTORY = 6
APPLICATION_ROOT_TOPIC = 7
CONFIGURED_DSSID = 8
CONFIGURED_VCID = 9
CREATE_TIME = 10
FSW_DICTIONARY_DIR = 11
FSW_DICTIONARY_VERSION = 12
MESSAGE_COUNTER = 13
MESSAGE_TYPE = 14
MISSION_ID = 15
MISSION_NAME = 16
PERSPECTIVE_ID = 17
SOURCE_PID = 18
SPACECRAFT_ID = 19
SPACECRAFT_NAME = 20
SSE_DICTIONARY_DIR = 21
SSE_DICTIONARY_VERSION = 22
TELEMETRY_STREAM_TYPE = 23
TESTBED_NAME = 24
VENUE_TYPE = 25
AMPCS_VERSION = 26



_PROTO3METADATAMAPELEMENT = _descriptor.Descriptor(
  name='Proto3MetadataMapElement',
  full_name='metadata.Proto3MetadataMapElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='metadata.Proto3MetadataMapElement.key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boolValue', full_name='metadata.Proto3MetadataMapElement.boolValue', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberValue', full_name='metadata.Proto3MetadataMapElement.numberValue', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longValue', full_name='metadata.Proto3MetadataMapElement.longValue', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doubleValue', full_name='metadata.Proto3MetadataMapElement.doubleValue', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floatValue', full_name='metadata.Proto3MetadataMapElement.floatValue', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringValue', full_name='metadata.Proto3MetadataMapElement.stringValue', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unsignedNumberValue', full_name='metadata.Proto3MetadataMapElement.unsignedNumberValue', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unsignedLongValue', full_name='metadata.Proto3MetadataMapElement.unsignedLongValue', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='metadata.Proto3MetadataMapElement.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=51,
  serialized_end=321,
)

_PROTO3METADATAMAPELEMENT.fields_by_name['key'].enum_type = _PROTO3METADATAKEY
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['boolValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['boolValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['numberValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['numberValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['longValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['longValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['doubleValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['doubleValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['floatValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['floatValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['stringValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['stringValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['unsignedNumberValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['unsignedNumberValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
_PROTO3METADATAMAPELEMENT.oneofs_by_name['value'].fields.append(
  _PROTO3METADATAMAPELEMENT.fields_by_name['unsignedLongValue'])
_PROTO3METADATAMAPELEMENT.fields_by_name['unsignedLongValue'].containing_oneof = _PROTO3METADATAMAPELEMENT.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Proto3MetadataMapElement'] = _PROTO3METADATAMAPELEMENT
DESCRIPTOR.enum_types_by_name['Proto3MetadataKey'] = _PROTO3METADATAKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3MetadataMapElement = _reflection.GeneratedProtocolMessageType('Proto3MetadataMapElement', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3METADATAMAPELEMENT,
  __module__ = 'primitives.metadata_primitives_pb2'
  # @@protoc_insertion_point(class_scope:metadata.Proto3MetadataMapElement)
  ))
_sym_db.RegisterMessage(Proto3MetadataMapElement)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
