# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitives/time_primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitives/time_primitives.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n%jpl.gds.serialization.primitives.timeB\"ProtoBufTimePrimitiveSerializationH\001P\001'),
  serialized_pb=_b('\n primitives/time_primitives.proto\",\n\nProto3Sclk\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x03\".\n\tProto3Lst\x12\x14\n\x0cmilliseconds\x18\x01 \x01(\x03\x12\x0b\n\x03sol\x18\x02 \x01(\x05\"6\n\tProto3Adt\x12\x14\n\x0cmilliseconds\x18\x01 \x01(\x03\x12\x13\n\x0bnanoseconds\x18\x02 \x01(\x03\"E\n\x0fProto3SclkRange\x12\x18\n\x03min\x18\x01 \x01(\x0b\x32\x0b.Proto3Sclk\x12\x18\n\x03max\x18\x02 \x01(\x0b\x32\x0b.Proto3Sclk\"B\n\x0eProto3ErtRange\x12\x17\n\x03min\x18\x01 \x01(\x0b\x32\n.Proto3Adt\x12\x17\n\x03max\x18\x02 \x01(\x0b\x32\n.Proto3Adt\"B\n\x0eProto3RctRange\x12\x17\n\x03min\x18\x01 \x01(\x0b\x32\n.Proto3Adt\x12\x17\n\x03max\x18\x02 \x01(\x0b\x32\n.Proto3Adt\"C\n\x0fProto3ScetRange\x12\x17\n\x03min\x18\x01 \x01(\x0b\x32\n.Proto3Adt\x12\x17\n\x03max\x18\x02 \x01(\x0b\x32\n.Proto3Adt\"K\n\x12Proto3SclkEncoding\x12\x12\n\ncoarseBits\x18\x01 \x01(\r\x12\x10\n\x08\x66ineBits\x18\x02 \x01(\r\x12\x0f\n\x07maxFine\x18\x03 \x01(\x04\x42O\n%jpl.gds.serialization.primitives.timeB\"ProtoBufTimePrimitiveSerializationH\x01P\x01\x62\x06proto3')
)




_PROTO3SCLK = _descriptor.Descriptor(
  name='Proto3Sclk',
  full_name='Proto3Sclk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='Proto3Sclk.seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanos', full_name='Proto3Sclk.nanos', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=80,
)


_PROTO3LST = _descriptor.Descriptor(
  name='Proto3Lst',
  full_name='Proto3Lst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='milliseconds', full_name='Proto3Lst.milliseconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol', full_name='Proto3Lst.sol', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=128,
)


_PROTO3ADT = _descriptor.Descriptor(
  name='Proto3Adt',
  full_name='Proto3Adt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='milliseconds', full_name='Proto3Adt.milliseconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanoseconds', full_name='Proto3Adt.nanoseconds', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=184,
)


_PROTO3SCLKRANGE = _descriptor.Descriptor(
  name='Proto3SclkRange',
  full_name='Proto3SclkRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='Proto3SclkRange.min', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Proto3SclkRange.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=255,
)


_PROTO3ERTRANGE = _descriptor.Descriptor(
  name='Proto3ErtRange',
  full_name='Proto3ErtRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='Proto3ErtRange.min', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Proto3ErtRange.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=323,
)


_PROTO3RCTRANGE = _descriptor.Descriptor(
  name='Proto3RctRange',
  full_name='Proto3RctRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='Proto3RctRange.min', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Proto3RctRange.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=391,
)


_PROTO3SCETRANGE = _descriptor.Descriptor(
  name='Proto3ScetRange',
  full_name='Proto3ScetRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='Proto3ScetRange.min', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Proto3ScetRange.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=460,
)


_PROTO3SCLKENCODING = _descriptor.Descriptor(
  name='Proto3SclkEncoding',
  full_name='Proto3SclkEncoding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coarseBits', full_name='Proto3SclkEncoding.coarseBits', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fineBits', full_name='Proto3SclkEncoding.fineBits', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxFine', full_name='Proto3SclkEncoding.maxFine', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=537,
)

_PROTO3SCLKRANGE.fields_by_name['min'].message_type = _PROTO3SCLK
_PROTO3SCLKRANGE.fields_by_name['max'].message_type = _PROTO3SCLK
_PROTO3ERTRANGE.fields_by_name['min'].message_type = _PROTO3ADT
_PROTO3ERTRANGE.fields_by_name['max'].message_type = _PROTO3ADT
_PROTO3RCTRANGE.fields_by_name['min'].message_type = _PROTO3ADT
_PROTO3RCTRANGE.fields_by_name['max'].message_type = _PROTO3ADT
_PROTO3SCETRANGE.fields_by_name['min'].message_type = _PROTO3ADT
_PROTO3SCETRANGE.fields_by_name['max'].message_type = _PROTO3ADT
DESCRIPTOR.message_types_by_name['Proto3Sclk'] = _PROTO3SCLK
DESCRIPTOR.message_types_by_name['Proto3Lst'] = _PROTO3LST
DESCRIPTOR.message_types_by_name['Proto3Adt'] = _PROTO3ADT
DESCRIPTOR.message_types_by_name['Proto3SclkRange'] = _PROTO3SCLKRANGE
DESCRIPTOR.message_types_by_name['Proto3ErtRange'] = _PROTO3ERTRANGE
DESCRIPTOR.message_types_by_name['Proto3RctRange'] = _PROTO3RCTRANGE
DESCRIPTOR.message_types_by_name['Proto3ScetRange'] = _PROTO3SCETRANGE
DESCRIPTOR.message_types_by_name['Proto3SclkEncoding'] = _PROTO3SCLKENCODING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3Sclk = _reflection.GeneratedProtocolMessageType('Proto3Sclk', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3SCLK,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3Sclk)
  ))
_sym_db.RegisterMessage(Proto3Sclk)

Proto3Lst = _reflection.GeneratedProtocolMessageType('Proto3Lst', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3LST,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3Lst)
  ))
_sym_db.RegisterMessage(Proto3Lst)

Proto3Adt = _reflection.GeneratedProtocolMessageType('Proto3Adt', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ADT,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3Adt)
  ))
_sym_db.RegisterMessage(Proto3Adt)

Proto3SclkRange = _reflection.GeneratedProtocolMessageType('Proto3SclkRange', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3SCLKRANGE,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3SclkRange)
  ))
_sym_db.RegisterMessage(Proto3SclkRange)

Proto3ErtRange = _reflection.GeneratedProtocolMessageType('Proto3ErtRange', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3ERTRANGE,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3ErtRange)
  ))
_sym_db.RegisterMessage(Proto3ErtRange)

Proto3RctRange = _reflection.GeneratedProtocolMessageType('Proto3RctRange', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3RCTRANGE,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3RctRange)
  ))
_sym_db.RegisterMessage(Proto3RctRange)

Proto3ScetRange = _reflection.GeneratedProtocolMessageType('Proto3ScetRange', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3SCETRANGE,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3ScetRange)
  ))
_sym_db.RegisterMessage(Proto3ScetRange)

Proto3SclkEncoding = _reflection.GeneratedProtocolMessageType('Proto3SclkEncoding', (_message.Message,), dict(
  DESCRIPTOR = _PROTO3SCLKENCODING,
  __module__ = 'primitives.time_primitives_pb2'
  # @@protoc_insertion_point(class_scope:Proto3SclkEncoding)
  ))
_sym_db.RegisterMessage(Proto3SclkEncoding)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
