/*
 * Copyright 2006-2018. California Institute of Technology.
 * ALL RIGHTS RESERVED.
 * U.S. Government sponsorship acknowledged.
 *
 * This software is subject to U. S. export control laws and
 * regulations (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the
 * extent that the software is subject to U.S. export control laws
 * and regulations, the recipient has the responsibility to obtain
 * export licenses or other export authority as may be required
 * before exporting such information to foreign countries or
 * providing access to foreign nationals.
 */
package jpl.gds.tc.impl.icmd;

import jpl.gds.tc.api.IUplinkMetadata;

/**
 * This class contains AMPCS metadata that is piggybacked on CPD requests. It
 * provides facilities to convert the metadata to a String to send with a CPD
 * request and to convert the metadata string back into this Java object upon
 * receiving it from a CPD poll.
 * 
 * @since AMPCS R3
 */
public class UplinkMetadata implements IUplinkMetadata {
    private static final String ELEMENT_DELIMITER = ",";
    private static final String KEY_VALUE_DELIMITER = "=";

    private static final String SESSION_ID_KEY = "sessionId";
    private static final String HOST_ID_KEY = "hostId";
    private static final String JMS_TOPIC_NAME_KEY = "jmsTopicName";
    private static final String SCID_KEY = "scid";

    private long sessionId;
    private int hostId;
    private String jmsTopicName;
    private int scid;

    /**
     * Constructor
     * 
     * @param sessionId the AMPCS session ID
     * @param hostId the AMPCS host ID
     * @param jmsTopicName the AMPCS message topic name
     * @param scid the spacecraft ID
     */
    public UplinkMetadata(final long sessionId, final int hostId,
            final String jmsTopicName, final int scid) {
        this.sessionId = sessionId;
        this.hostId = hostId;
        this.jmsTopicName = jmsTopicName;
        this.scid = scid;
    }

    /**
     * Constructor. This constructor instantiates the CommandMetadata object
     * using a metadata string generated by another instance of this class.
     * 
     * @param metadataString the metadata string generated by another instance
     *            of this class
     */
    public UplinkMetadata(final String metadataString) {
        this.sessionId = -1;
        this.hostId = -1;
        this.jmsTopicName = null;
        this.scid = -1;

        if (metadataString == null) {
            return;
        }

        final String[] keyValues = metadataString.split(ELEMENT_DELIMITER);

        for (final String kv : keyValues) {
            final String[] keyValueArr = kv.split(KEY_VALUE_DELIMITER);

            if (keyValueArr.length < 2) {
                continue;
            }

            try {
                if (keyValueArr[0].equals(SESSION_ID_KEY)) {
                    this.sessionId = Long.parseLong(keyValueArr[1]);
                } else if (keyValueArr[0].equals(HOST_ID_KEY)) {
                    this.hostId = Integer.parseInt(keyValueArr[1]);
                } else if (keyValueArr[0].equals(JMS_TOPIC_NAME_KEY)) {
                    this.jmsTopicName = keyValueArr[1].equalsIgnoreCase("null") ? null
                            : keyValueArr[1];
                } else if (keyValueArr[0].equals(SCID_KEY)) {
                    this.scid = Integer.parseInt(keyValueArr[1]);
                }
            } catch (final Exception e) {
                continue;
            }
        }
    }

    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#getSessionId()
     */
    @Override
    public long getSessionId() {
        return this.sessionId;
    }

    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#getHostId()
     */
    @Override
    public int getHostId() {
        return this.hostId;
    }

    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#getMessageServiceTopicName()
     */
    @Override
    public String getMessageServiceTopicName() {
        return this.jmsTopicName;
    }

    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#setMessageServiceTopicName(java.lang.String)
     */
    @Override
    public void setMessageServiceTopicName(final String topic) {
        this.jmsTopicName = topic;
    }

    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#getScid()
     */
    @Override
    public int getScid() {
        return this.scid;
    }


    /**
     * @{inheritDoc}
     * @see jpl.gds.tc.api.IUplinkMetadata#toMetadataString()
     */
    @Override
    public String toMetadataString() {
        final StringBuilder sb = new StringBuilder();
        sb.append(SESSION_ID_KEY);
        sb.append(KEY_VALUE_DELIMITER);
        sb.append(this.sessionId);
        sb.append(ELEMENT_DELIMITER);
        sb.append(HOST_ID_KEY);
        sb.append(KEY_VALUE_DELIMITER);
        sb.append(this.hostId);
        sb.append(ELEMENT_DELIMITER);
        sb.append(JMS_TOPIC_NAME_KEY);
        sb.append(KEY_VALUE_DELIMITER);
        sb.append(this.jmsTopicName);
        sb.append(ELEMENT_DELIMITER);
        sb.append(SCID_KEY);
        sb.append(KEY_VALUE_DELIMITER);
        sb.append(this.scid);

        return sb.toString();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return this.toMetadataString();
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (prime * result) + this.hostId;
        result = (prime * result)
                + ((this.jmsTopicName == null) ? 0 : this.jmsTopicName
                        .hashCode());
        result = (prime * result) + this.scid;
        result = (prime * result)
                + (int) (this.sessionId ^ (this.sessionId >>> 32));
        return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (this.getClass() != obj.getClass()) {
            return false;
        }
        final UplinkMetadata other = (UplinkMetadata) obj;
        if (this.hostId != other.hostId) {
            return false;
        }
        if (this.jmsTopicName == null) {
            if (other.jmsTopicName != null) {
                return false;
            }
        } else if (!this.jmsTopicName.equals(other.jmsTopicName)) {
            return false;
        }
        if (this.scid != other.scid) {
            return false;
        }
        if (this.sessionId != other.sessionId) {
            return false;
        }
        return true;
    }

}
